### ISSUE TITLE
Minified version is old

### ISSUE THREAD

**Issue by amedeedaboville** [mike-zarandona/StickyStack.js#1]
The .min.js version in the repository is 1.1.1 and doesn't match the unminified version (1.1.2)

I spent a while trying to figure out why the "cards with viewport taller than the screen" weren't working, though the most recent commit had fixed it.

Thanks for the plugin!

**Comment by mike-zarandona** [comment]
Ah bummer - sorry to hear that, but glad you got it sorted.  I'll get this updated shortly, thanks for the heads up!

P.S. - if you wind up using it in production anywhere, I'd love to see the results.

**Comment by amedeedaboville** [comment]
No problem. 
I'm using it for justhack.io, as I didn't want to learn and download a huge parallax library like skrollr or scrollmagic.
