### ISSUE TITLE
scrolling option

### ISSUE THREAD

**Issue by Daewl** [mike-zarandona/StickyStack.js#5]
is there a chance to use this plugin something like changing content only with 1 scroll not full scroll

scroll sample 
http://www.jqueryscript.net/demo/Smooth-Fullscreen-Scrolling-Effect-with-jQuery-ScrollBetweenElements/

**Comment by mike-zarandona** [comment]
I'm not sure what this means, can you elaborate?

> only with 1 scroll not full scroll

**Comment by mike-zarandona** [comment]
I see now - the example posted was not working on mobile.  StickyStack's purpose is to do one thing and one thing very well - to create a stacking effect by sticking panels to the top of the viewport.  Adding panel-by-panel scrolling would be a departure from this core functionality, however feel free to fork and combine with other plugins, or write the custom functionality required.
